- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIpvWjgWHVIhBEFglWhXdCGodESR8vojOPGvrNiyG6Jx ansible"

- name: generate ssh_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file}}"
    dest: /etc/ssh/sshd_config
    owner: nilesh
    group: root
    mode: 0644
  notify: restart_sshd
