- name: install unzip
  homebrew:
    name: unzip
  become: false

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.10.4/terraform_1.10.4_linux_386.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: user
    group: staff
